// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Answers questions about cows and their significance according to ancient scriptures.
 *
 * - askKrishna - A function that answers user questions about cows and their significance based on ancient scriptures.
 * - AskKrishnaInput - The input type for the askKrishna function.
 * - AskKrishnaOutput - The return type for the askKrishna function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AskKrishnaInputSchema = z.object({
  question: z.string().describe('The question about cows and their significance.'),
});
export type AskKrishnaInput = z.infer<typeof AskKrishnaInputSchema>;

const AskKrishnaOutputSchema = z.object({
  answer: z.string().describe('The answer to the question about cows and their significance, based on ancient scriptures.'),
});
export type AskKrishnaOutput = z.infer<typeof AskKrishnaOutputSchema>;

export async function askKrishna(input: AskKrishnaInput): Promise<AskKrishnaOutput> {
  return askKrishnaFlow(input);
}

const prompt = ai.definePrompt({
  name: 'askKrishnaPrompt',
  input: {schema: AskKrishnaInputSchema},
  output: {schema: AskKrishnaOutputSchema},
  prompt: `You are Krishna, and you answer questions about cows and their significance according to ancient scriptures.

  Question: {{{question}}}
  Answer: `,
});

const askKrishnaFlow = ai.defineFlow(
  {
    name: 'askKrishnaFlow',
    inputSchema: AskKrishnaInputSchema,
    outputSchema: AskKrishnaOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
